'use client'

import * as React from 'react'
import { useTranslations } from 'next-intl'
import {
  Sheet,
  SheetBody,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  Button,
  Input,
  Label,
} from '@sassy-auth/ui'
import { createAppAction } from '@/app/(admin)/apps/actions'

interface Props {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function AppCreateDrawer({ open, onOpenChange }: Props) {
  const t = useTranslations()
  const [name, setName] = React.useState('')
  const [url, setUrl] = React.useState('')
  const [errorKey, setErrorKey] = React.useState<string | null>(null)
  const [pending, startTransition] = React.useTransition()

  React.useEffect(() => {
    if (!open) {
      setName('')
      setUrl('')
      setErrorKey(null)
    }
  }, [open])

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!name.trim()) {
      setErrorKey('apps.errors.nameRequired')
      return
    }
    setErrorKey(null)
    startTransition(async () => {
      const result = await createAppAction({ name: name.trim(), url: url.trim() })
      if ('errorKey' in result) setErrorKey(result.errorKey)
      else onOpenChange(false)
    })
  }

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent>
        <SheetHeader>
          <div>
            <SheetTitle>{t('apps.drawer.createTitle')}</SheetTitle>
            <SheetDescription>{t('apps.drawer.createSubtitle')}</SheetDescription>
          </div>
        </SheetHeader>
        <SheetBody>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <Label htmlFor="appName">{t('apps.fields.name')}</Label>
              <Input
                id="appName"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
              />
            </div>
            <div>
              <Label htmlFor="appUrl">{t('apps.fields.url')}</Label>
              <Input
                id="appUrl"
                type="url"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                required
                placeholder="https://app.example.com"
              />
              <p className="mt-1 text-body-sm text-[var(--muted-foreground)]">
                {t('apps.fields.urlHint')}
              </p>
            </div>
            <div className="rounded border border-[var(--border)] bg-[var(--muted)] p-3 text-body-sm text-[var(--muted-foreground)]">
              <span className="material-symbols-outlined align-middle text-[16px] text-[var(--primary)]">
                info
              </span>{' '}
              {t('apps.drawer.identifiersAutoGenerated')}
            </div>
            {errorKey && (
              <p role="alert" className="text-body-sm text-[var(--destructive)]">
                {t(errorKey)}
              </p>
            )}
            <div className="flex justify-end gap-2 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={() => onOpenChange(false)}
                disabled={pending}
              >
                {t('apps.drawer.cancel')}
              </Button>
              <Button type="submit" disabled={pending}>
                {pending ? t('apps.drawer.saving') : t('apps.drawer.createTitle')}
              </Button>
            </div>
          </form>
        </SheetBody>
      </SheetContent>
    </Sheet>
  )
}
