'use client'

import * as React from 'react'
import Link from 'next/link'
import { useTranslations } from 'next-intl'
import {
  Sheet, SheetBody, SheetContent, SheetDescription, SheetHeader, SheetTitle,
  Button, ButtonGroup, Input, Label,
} from '@sassy-auth/ui'
import { createOrgAction } from '@/app/(admin)/orgs/actions'
import type { App } from '@/lib/types'

interface Props {
  apps: App[]
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function OrgCreateDrawer({ apps, open, onOpenChange }: Props) {
  const t = useTranslations()
  const [name, setName] = React.useState('')
  const [appId, setAppId] = React.useState('')
  const [errorKey, setErrorKey] = React.useState<string | null>(null)
  const [pending, startTransition] = React.useTransition()

  const nonPlatformApps = React.useMemo(() => apps.filter((a) => !a.isPlatform), [apps])
  const noApps = nonPlatformApps.length === 0

  React.useEffect(() => {
    if (!open) {
      setName('')
      setAppId('')
      setErrorKey(null)
    }
  }, [open])

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (noApps) return
    if (!appId) {
      setErrorKey('orgs.errors.appRequired')
      return
    }
    if (!name.trim()) {
      setErrorKey('orgs.errors.nameRequired')
      return
    }
    setErrorKey(null)
    startTransition(async () => {
      const result = await createOrgAction({ name: name.trim(), appId })
      if ('errorKey' in result) setErrorKey(result.errorKey)
      else onOpenChange(false)
    })
  }

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent>
        <SheetHeader>
          <div>
            <SheetTitle>{t('orgs.drawer.createTitle')}</SheetTitle>
            <SheetDescription>{t('orgs.drawer.createSubtitle')}</SheetDescription>
          </div>
        </SheetHeader>
        <SheetBody>
          <form onSubmit={handleSubmit} className="space-y-4">
            {noApps ? (
              <div className="rounded border border-border bg-muted p-3 text-body-sm text-muted-foreground">
                {t('orgs.drawer.noNonPlatformApps')}{' '}
                <Link href="/apps" className="text-primary hover:underline">
                  {t('orgs.drawer.goToApps')}
                </Link>
              </div>
            ) : (
              <div>
                <Label htmlFor="orgApp">{t('orgs.fields.app')}</Label>
                <select
                  id="orgApp"
                  value={appId}
                  onChange={(e) => setAppId(e.target.value)}
                  required
                  className="mt-1 block h-9 w-full rounded border border-border bg-card px-2 text-body-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                >
                  <option value="" disabled>—</option>
                  {nonPlatformApps.map((a) => (
                    <option key={a.publicId} value={a.publicId}>{a.name}</option>
                  ))}
                </select>
              </div>
            )}
            <div>
              <Label htmlFor="orgName">{t('orgs.fields.name')}</Label>
              <Input
                id="orgName"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
                disabled={noApps}
              />
            </div>
            <div className="rounded border border-border bg-muted p-3 text-body-sm text-muted-foreground">
              <span className="material-symbols-outlined align-middle text-[16px] text-primary">
                info
              </span>{' '}
              {t('orgs.drawer.identifiersAutoGenerated')}
            </div>
            {errorKey && (
              <p role="alert" className="text-body-sm text-destructive">
                {t(errorKey)}
              </p>
            )}
            <div className="flex justify-end pt-4">
              <ButtonGroup>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => onOpenChange(false)}
                  disabled={pending}
                >
                  {t('orgs.drawer.cancel')}
                </Button>
                <Button type="submit" disabled={pending || noApps}>
                  {pending ? t('orgs.drawer.saving') : t('orgs.drawer.createTitle')}
                </Button>
              </ButtonGroup>
            </div>
          </form>
        </SheetBody>
      </SheetContent>
    </Sheet>
  )
}
